from termcolor import colored

from . import choppercommand
from .adventure import _detect_objects_adventure
from .alien import _detect_objects_alien
from .amidar import _detect_objects_amidar
from .assault import _detect_objects_assault
from .asterix import _detect_objects_asterix
from .asteroids import _detect_objects_asteroids
from .atlantis import _detect_objects_atlantis
from .bankheist import _detect_objects_bankheist
from .battlezone import _detect_objects_battlezone
from .beamrider import _detect_objects_beamrider
from .berzerk import _detect_objects_berzerk
from .bowling import _detect_objects_bowling
from .boxing import _detect_objects_boxing
from .breakout import _detect_objects_breakout
from .carnival import _detect_objects_carnival
from .centipede import _detect_objects_centipede
from .crazyclimber import _detect_objects_crazyclimber
from .donkeykong import _detect_objects_donkeykong
from .demonattack import _detect_objects_demon_attack
from .enduro import _detect_objects_enduro
from .fishingderby import _detect_objects_fishingderby
from .freeway import _detect_objects_freeway
from .frostbite import _detect_objects_frostbite
from .galaxian import _detect_objects_galaxian
from .gopher import _detect_objects_gopher
from .hero import _detect_objects_hero
from .icehockey import _detect_objects_icehockey
from .jamesbond import _detect_objects_jamesbond
from .kangaroo import _detect_objects_kangaroo
from .krull import _detect_objects_krull
from .montezumarevenge import _detect_objects_montezumarevenge
from .mspacman import _detect_objects_mspacman
from .pacman import _detect_objects_pacman
from .pitfall import _detect_objects_pitfall
from .pong import _detect_objects_pong
from .privateeye import _detect_objects_privateeye
from .qbert import _detect_objects_qbert
from .riverraid import _detect_objects_riverraid
from .roadrunner import _detect_objects_roadrunner
from .seaquest import _detect_objects_seaquest
from .skiing import _detect_objects_skiing
from .spaceinvaders import _detect_objects_spaceinvaders
from .tennis import _detect_objects_tennis
from .timepilot import _detect_objects_timepilot
from .upndown import _detect_objects_upndown
from .venture import _detect_objects_venture
from .videopinball import _detect_objects_videopinball
from .yarsrevenge import _detect_objects_yarsrevenge


def detect_objects_vision(objects, obs, game_name, hud=False):
    if game_name.lower() == "atlantis":
        return _detect_objects_atlantis(objects, obs, hud)
    elif game_name.lower() == "freeway":
        return _detect_objects_freeway(objects, obs, hud)
    elif game_name.lower() == "bowling":
        return _detect_objects_bowling(objects, obs, hud)
    elif game_name.lower() == "boxing":
        return _detect_objects_boxing(objects, obs, hud)
    elif game_name.lower() == "roadrunner":
        return _detect_objects_roadrunner(objects, obs, hud)
    elif game_name.lower() == "pong":
        return _detect_objects_pong(objects, obs, hud)
    elif game_name.lower() == "seaquest":
        return _detect_objects_seaquest(objects, obs, hud)
    elif game_name.lower() == "skiing":
        return _detect_objects_skiing(objects, obs, hud)
    elif game_name.lower() == "tennis":
        return _detect_objects_tennis(objects, obs, hud)
    elif game_name.lower() == "bowling":
        return _detect_objects_bowling(objects, obs, hud)
    elif game_name.lower() == "kangaroo":
        return _detect_objects_kangaroo(objects, obs, hud)
    elif game_name.lower() == "spaceinvaders":
        return _detect_objects_spaceinvaders(objects, obs, hud)
    elif game_name.lower() == "demonattack":
        return _detect_objects_demon_attack(objects, obs, hud)
    elif game_name.lower() == "breakout":
        return _detect_objects_breakout(objects, obs, hud)
    elif game_name.lower() == "mspacman":
        return _detect_objects_mspacman(objects, obs, hud)
    elif game_name.lower() == "pacman":
        return _detect_objects_pacman(objects, obs, hud)
    elif game_name.lower() == "centipede":
        return _detect_objects_centipede(objects, obs, hud)
    elif game_name.lower() == "carnival":
        return _detect_objects_carnival(objects, obs, hud)
    elif game_name.lower() == "donkeykong":
        return _detect_objects_donkeykong(objects, obs, hud)
    elif game_name.lower() == "galaxian":
        return _detect_objects_galaxian(objects, obs, hud)
    elif game_name.lower() == "berzerk":
        return _detect_objects_berzerk(objects, obs, hud)
    elif game_name.lower() == "beamrider":
        return _detect_objects_beamrider(objects, obs, hud)
    elif game_name.lower() == "asterix":
        return _detect_objects_asterix(objects, obs, hud)
    elif game_name.lower() == "choppercommand":
        return choppercommand._detect_objects(objects, obs, hud)
    elif game_name.lower() == "qbert":
        return _detect_objects_qbert(objects, obs, hud)
    elif game_name.lower() == "montezumarevenge":
        return _detect_objects_montezumarevenge(objects, obs, hud)
    elif game_name.lower() == "atlantis":
        return _detect_objects_atlantis(objects, obs, hud)
    elif game_name.lower() == "asteroids":
        return _detect_objects_asteroids(objects, obs, hud)
    elif game_name.lower() == "riverraid":
        return _detect_objects_riverraid(objects, obs, hud)
    elif game_name.lower() == "assault":
        return _detect_objects_assault(objects, obs, hud)
    elif game_name.lower() == "alien":
        return _detect_objects_alien(objects, obs, hud)
    elif game_name.lower() == "frostbite":
        return _detect_objects_frostbite(objects, obs, hud)
    elif game_name.lower() == "fishingderby":
        return _detect_objects_fishingderby(objects, obs, hud)
    elif game_name.lower() == "hero":
        return _detect_objects_hero(objects, obs, hud)
    elif game_name.lower() == "pitfall":
        return _detect_objects_pitfall(objects, obs, hud)
    elif game_name.lower() == "yarsrevenge":
        return _detect_objects_yarsrevenge(objects, obs, hud)
    elif game_name.lower() == "icehockey":
        return _detect_objects_icehockey(objects, obs, hud)
    elif game_name.lower() == "privateeye":
        return _detect_objects_privateeye(objects, obs, hud)
    elif game_name.lower() == "gopher":
        return _detect_objects_gopher(objects, obs, hud)
    elif game_name.lower() == "enduro":
        return _detect_objects_enduro(objects, obs, hud)
    elif game_name.lower() == "videopinball":
        return _detect_objects_videopinball(objects, obs, hud)
    elif game_name.lower() == "venture":
        return _detect_objects_venture(objects, obs, hud)
    elif game_name.lower() == "crazyclimber":
        return _detect_objects_crazyclimber(objects, obs, hud)
    elif game_name.lower() == "amidar":
        return _detect_objects_amidar(objects, obs, hud)
    elif game_name.lower() == "battlezone":
        return _detect_objects_battlezone(objects, obs, hud)
    elif game_name.lower() == "bankheist":
        return _detect_objects_bankheist(objects, obs, hud)
    elif game_name.lower() == "adventure":
        return _detect_objects_adventure(objects, obs, hud)
    elif game_name.lower() == "jamesbond":
        return _detect_objects_jamesbond(objects, obs, hud)
    elif game_name.lower() == "krull":
        return _detect_objects_krull(objects, obs, hud)
    elif game_name.lower() == "timepilot":
        return _detect_objects_timepilot(objects, obs, hud)
    elif game_name.lower() == "upndown":
        return _detect_objects_upndown(objects, obs, hud)
    else:
        raise NotImplementedError(colored("Uncovered game in vision mode", "red"))
